### ISSUE TITLE
Support for IntelliJ 2024.1

### ISSUE THREAD

**Issue by dzikoysk** [Jozott00/AdaptiveCaretScroll#10]
Hey, it'd be great to support the latest version of IntelliJ:

![obraz](https://github.com/Jozott00/AdaptiveCaretScroll/assets/4235722/f3fa9cae-f588-4b5f-b4fc-0c86307337c7)

It's still EAP, but it used to work for them.

**Comment by Jozott00** [comment]
Sorry for the very late response!

The plugin is now available for IntelliJ platform version 2024.1
