### ISSUE TITLE
Not able to select the last file line

### ISSUE THREAD

**Issue by Karuption** [Jozott00/AdaptiveCaretScroll#4]
If the file's last char is on the top half of the screen, you are not able to select the last line with a click.

https://github.com/Jozott00/AdaptiveCaretScroll/assets/538762/c39f2fac-af00-46d9-9753-d2d3d254b90b

**Comment by Jozott00** [comment]
Fixed in version 1.0.2. Should be available on the marketplace in the next couple of days.
