### ISSUE TITLE
Feature request - Percentage of visible lines instead of literal?

### ISSUE THREAD

**Issue by Ralithune** [Jozott00/AdaptiveCaretScroll#6]
Would it be possible to add a feature to specify percentage of visible lines as a buffer instead of a literal?

My use case is that I use PyCharm's "Problems" pane on the bottom to do a first debug pass, and when it's taking up half the screen my literal minimum values of 25 lines top / 25 lines bottom make it jump all over the place.

It would be cool if I could set something like 15% top / 15% bottom instead. :)

**Comment by Jozott00** [comment]
Create idea! Thanks for the report!

The next version contains relative paddings.

It will also handle the case for absolute line paddings. If the paddings overlap, the scrolling falls back to centered scrolling. This avoids the weird jumping with small editors!

**Comment by Jozott00** [comment]
Version 1.1.0 is now available on Jetbrain's marketplace.
