### ISSUE TITLE
Not compatible with the version of your running IDE (RubyMine 2023.3)

### ISSUE THREAD

**Issue by kylesnowschwartz** [Jozott00/AdaptiveCaretScroll#7]
Hello! You may already be aware but the latest version of RubyMine claims that adaptive caret scroll is no longer compatible. I can no longer enable the package.

I love this plugin and hope it'll be brought up to date with the latest versions!

Cheerio
Kyle
<img width="1286" alt="Screenshot 2023-12-09 at 11 25 33 AM" src="https://github.com/Jozott00/AdaptiveCaretScroll/assets/11069001/44947009-7e26-484e-84a3-6c7924d522ce">

**Comment by Jozott00** [comment]
Hello, thank you for your issue! Unfortunately I've been a bit busy lately. I will try to solve the problem by tomorrow!

**Comment by Jozott00** [comment]
@kylesnowschwartz The new version v1.1.1 has finally been approved. As far as I've tested it, everything works on Intellij, but I experienced centered scrolling issues on the RustRover EAP. Does the plugin work fine for you on RubyMine?

**Comment by kylesnowschwartz** [comment]
Yes working again after updating the plugin and restarting. Awesome!!!
